package env

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/devkit/devkit/internal/config"
	"github.com/devkit/devkit/pkg/logger"
	"github.com/spf13/cobra"
)

func NewEnvCommand() *cobra.Command {
	var outputFile string
	var show bool

	cmd := &cobra.Command{
		Use:   "env",
		Short: "Generate or show environment variables for services",
		Run: func(cmd *cobra.Command, args []string) {
			if show {
				showEnv()
				return
			}

			generateEnv(outputFile)
		},
	}

	cmd.Flags().StringVarP(&outputFile, "output", "o", ".env", "Output file")
	cmd.Flags().BoolVarP(&show, "show", "s", false, "Show current environment variables")
	return cmd
}

func showEnv() {
	logger.Header("Environment Variables")

	envFile := ".env"
	data, err := os.ReadFile(envFile)
	if err != nil {
		logger.Warn("No .env file found. Run: dev env")
		return
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := parts[0]
			val := parts[1]
			if len(val) > 20 {
				val = val[:20] + "..."
			}
			logger.Step(fmt.Sprintf("%s=%s", key, val))
		}
	}
}

func getRunningServices() []string {
	cmd := exec.Command("docker", "ps", "--filter", "name=devkit-", "--format", "{{.Names}}")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return nil
	}

	var services []string
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			name := strings.TrimPrefix(line, "devkit-")
			services = append(services, name)
		}
	}
	return services
}

func generateEnv(outputFile string) {
	cfg, _ := config.Load()

	// Also detect running devkit containers
	runningContainers := getRunningServices()
	
	// Merge config services with running containers
	serviceNames := map[string]bool{}
	if cfg != nil {
		for _, svc := range cfg.Services {
			serviceNames[svc.Name] = true
		}
	}
	for _, name := range runningContainers {
		serviceNames[name] = true
	}

	var lines []string
	lines = append(lines, "# Generated by DevKit — do not edit manually")
	lines = append(lines, "# Run: dev env to regenerate")
	lines = append(lines, "")

	count := 0
	for name := range serviceNames {
		switch name {
		case "postgres", "postgresql":
			lines = append(lines, "# PostgreSQL")
			lines = append(lines, "DATABASE_URL=postgresql://postgres:devkit123@localhost:5432/devkit")
			lines = append(lines, "POSTGRES_USER=postgres")
			lines = append(lines, "POSTGRES_PASSWORD=devkit123")
			lines = append(lines, "POSTGRES_DB=devkit")
			lines = append(lines, "POSTGRES_HOST=localhost")
			lines = append(lines, "POSTGRES_PORT=5432")
			lines = append(lines, "")
			count++

		case "redis":
			lines = append(lines, "# Redis")
			lines = append(lines, "REDIS_URL=redis://localhost:6379")
			lines = append(lines, "REDIS_HOST=localhost")
			lines = append(lines, "REDIS_PORT=6379")
			lines = append(lines, "")
			count++

		case "mysql":
			lines = append(lines, "# MySQL")
			lines = append(lines, "DATABASE_URL=mysql://devkit:devkit123@localhost:3306/devkit")
			lines = append(lines, "MYSQL_ROOT_PASSWORD=devkit123")
			lines = append(lines, "MYSQL_USER=devkit")
			lines = append(lines, "MYSQL_PASSWORD=devkit123")
			lines = append(lines, "MYSQL_DATABASE=devkit")
			lines = append(lines, "")
			count++

		case "mongo", "mongodb":
			lines = append(lines, "# MongoDB")
			lines = append(lines, "MONGODB_URL=mongodb://devkit:devkit123@localhost:27017/devkit?authSource=admin")
			lines = append(lines, "MONGO_INITDB_ROOT_USERNAME=devkit")
			lines = append(lines, "MONGO_INITDB_ROOT_PASSWORD=devkit123")
			lines = append(lines, "")
			count++

		case "minio":
			lines = append(lines, "# MinIO (S3-compatible)")
			lines = append(lines, "MINIO_ENDPOINT=localhost:9000")
			lines = append(lines, "MINIO_ACCESS_KEY=devkit")
			lines = append(lines, "MINIO_SECRET_KEY=devkit123")
			lines = append(lines, "MINIO_ROOT_USER=devkit")
			lines = append(lines, "MINIO_ROOT_PASSWORD=devkit123")
			lines = append(lines, "S3_BUCKET=devkit-bucket")
			lines = append(lines, "")
			count++
		}
	}

	if len(lines) <= 3 {
		logger.Info("No services configured. Add services to devkit.json")
		return
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(outputFile, []byte(content), 0644); err != nil {
		logger.Error(fmt.Sprintf("Failed to write %s: %s", outputFile, err))
		os.Exit(1)
	}

	logger.Success(fmt.Sprintf("Generated %s with %d services", outputFile, len(cfg.Services)))
}
