package verify

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestAttributionGeneratedMarker(t *testing.T) {
	files := map[string]fileContent{
		"gen.ts": {contents: []string{"// This file was generated by Copilot", "const x = 1;"}},
	}
	per := scoreAttribution(files)
	a := per["gen.ts"]
	if a.AiLines != 1 {
		t.Fatalf("expected 1 AI line, got %d", a.AiLines)
	}
	if a.Label != "High" {
		t.Fatalf("expected High label for 1/2 lines (50%%), got %s", a.Label)
	}
}

func TestAttributionEchoComment(t *testing.T) {
	lines := []string{"// increment the counter by one", "counter = counter + 1", "return counter"}
	a := attributionFor("x.py", lines)
	if a.AiLines < 1 {
		t.Fatal("echo comment should be attributed as AI")
	}
}

func TestAttributionCleanCode(t *testing.T) {
	lines := []string{"export function sum(a: number, b: number) {", "  return a + b;", "}"}
	a := attributionFor("ok.ts", lines)
	if a.AiLines != 0 {
		t.Fatalf("clean code should have no AI lines, got %d", a.AiLines)
	}
	if a.Label != "None" {
		t.Fatalf("expected None label, got %s", a.Label)
	}
}

func TestAttributionEssayComment(t *testing.T) {
	lines := []string{
		"// This function handles the complex case of normalizing user input",
		"// across multiple locales and currency formats, being careful about",
		"// edge cases such as decimal separators and negative number handling",
		"// before returning the final normalized value to the caller",
		"func normalize(input string) string {",
	}
	a := attributionFor("x.go", lines)
	if a.AiLines < 1 {
		t.Fatal("essay-style comment block should be attributed as AI")
	}
}

func TestAttributionTypeWidening(t *testing.T) {
	lines := []string{"const opts: any = getUserConfig();"}
	a := attributionFor("x.ts", lines)
	if a.AiLines < 1 {
		t.Fatal("type widening (any) should be an AI signal")
	}
}

func TestAverageAttribution(t *testing.T) {
	per := map[string]attribution{
		"a.go": {AiLines: 5, Total: 10},
		"b.go": {AiLines: 0, Total: 10},
	}
	agg := averageAttribution(per)
	if agg.AiLines != 5 || agg.Total != 20 {
		t.Fatalf("unexpected aggregate: %+v", agg)
	}
	if agg.Pct != 0.25 {
		t.Fatalf("expected 0.25 pct, got %v", agg.Pct)
	}
	if agg.Label != "Moderate" {
		t.Fatalf("expected Moderate, got %s", agg.Label)
	}
}

func TestAnalyzeIncludesAttribution(t *testing.T) {
	files := map[string]fileContent{
		"a.ts": {contents: []string{"// generated with copilot", "const k = 1;"}, nums: []int{1, 2}},
	}
	r := analyze("staged", files, false)
	if r.AiSignal != "High" {
		t.Fatalf("expected High ai signal (1/2 = 50%%), got %s", r.AiSignal)
	}
	if r.AiLines != 1 || r.AiTotal != 2 {
		t.Fatalf("unexpected ai counts: %d/%d", r.AiLines, r.AiTotal)
	}
	if r.Attribution["a.ts"].AiLines != 1 {
		t.Fatalf("per-file attribution missing: %+v", r.Attribution)
	}
}

func TestFinalizeVerdictWithFailedTests(t *testing.T) {
	r := &Report{High: 0, Total: 1, Tests: TestResult{Ran: true, Passed: false}}
	finalizeVerdict(r)
	if r.Verdict != "BLOCK" {
		t.Fatalf("failed tests should block, got %s", r.Verdict)
	}

	r2 := &Report{High: 0, Total: 1, Tests: TestResult{Ran: true, Passed: true}}
	finalizeVerdict(r2)
	if r2.Verdict != "ACTION NEEDED" {
		t.Fatalf("passing tests with findings should be ACTION NEEDED, got %s", r2.Verdict)
	}

	r3 := &Report{High: 0, Total: 0, Tests: TestResult{Ran: true, Passed: true}}
	finalizeVerdict(r3)
	if r3.Verdict != "PASS" {
		t.Fatalf("clean + passing tests should PASS, got %s", r3.Verdict)
	}
}

func TestTestCommandMapping(t *testing.T) {
	cases := map[string]string{
		"go":      "go",
		"node":    "npm",
		"python":  "pytest",
		"rust":    "cargo",
		"java":    "mvn",
		"unknown": "",
	}
	for stack, want := range cases {
		bin, _ := testCommand(stack)
		if bin != want {
			t.Errorf("stack %q: expected %q, got %q", stack, want, bin)
		}
	}
}

func TestRenderHTMLIncludesSections(t *testing.T) {
	r := Report{
		Mode:     "staged",
		Verdict:  "BLOCK",
		Total:    1,
		High:     1,
		Risk:     "Critical",
		AiSignal: "High",
		AiLines:  2,
		AiTotal:  4,
		Files: []FileReport{{
			File: "app.ts", LineCount: 10,
			Findings: []Finding{{
				File: "app.ts", Line: 3, Rule: "hardcoded-secret", Category: "security",
				Severity: "high", Message: "hardcoded-secret", Suggestion: "Move to env",
			}},
		}},
		Attribution: map[string]attribution{"app.ts": {AiLines: 2, Total: 4, Pct: 0.5, Label: "High"}},
	}
	html := RenderHTML(r)
	for _, want := range []string{"VERDICT: BLOCK", "app.ts", "L3", "Critical", "Automated tests", "attribution is a heuristic"} {
		if !strings.Contains(html, want) {
			t.Errorf("html missing %q", want)
		}
	}
}

func TestJSONReportWithNewFields(t *testing.T) {
	files := map[string]fileContent{
		"a.go": {contents: []string{"// generated by AI assistant", "package main"}, nums: []int{1, 2}},
	}
	r := analyze("file", files, false)
	out, err := json.Marshal(r)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"aiSignal", "aiLines", "attribution"} {
		if !strings.Contains(string(out), want) {
			t.Errorf("json missing field %q", want)
		}
	}
}
