package verify

import (
	"fmt"
	"html"
	"os"
	"os/exec"
	"runtime"
	"strings"
)

// RenderHTML builds a standalone dark-themed visual report for the browser.
func RenderHTML(r Report) string {
	var b strings.Builder

	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Verification Report — devkit</title>\n<style>\n")
	b.WriteString(`*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,'Segoe UI',Roboto,sans-serif;background:#09090b;color:#e4e4e7;padding:32px 24px}
.wrap{max-width:960px;margin:0 auto}
h1{font-size:22px;color:#fff;margin-bottom:4px}
.mode{font-size:13px;color:#52525b;margin-bottom:24px}
.verdict{border-radius:12px;padding:22px 24px;margin-bottom:20px;font-weight:800;font-size:19px}
.verdict.pass{background:#16a34a22;color:#4ade80;border:1px solid #16a34a}
.verdict.action{background:#f59e0b22;color:#fbbf24;border:1px solid #f59e0b}
.verdict.block{background:#ef444422;color:#f87171;border:1px solid #ef4444}
.chips{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:26px}
.chip{background:#18181b;border:1px solid #27272a;border-radius:10px;padding:12px 18px;min-width:110px}
.chip .k{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:#71717a}
.chip .v{font-size:20px;font-weight:700;margin-top:2px}
.chip .v.red{color:#f87171}.chip .v.yellow{color:#fbbf24}.chip .v.green{color:#4ade80}.chip .v.cyan{color:#22d3ee}
.file{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:20px 22px;margin-bottom:16px}
.file h2{font-size:15px;color:#fff;margin-bottom:2px}
.file .meta{font-size:12px;color:#52525b;margin-bottom:14px}
.ai-bar{height:6px;background:#27272a;border-radius:4px;margin:8px 0 14px;overflow:hidden}
.ai-bar span{display:block;height:100%;background:#22d3ee}
.finding{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid #1c1c1f;font-size:13px}
.finding:last-child{border-bottom:none}
.sev{min-width:52px;font-weight:700;font-size:11px;padding:3px 8px;border-radius:6px;text-align:center;height:fit-content}
.sev.high{background:#ef444422;color:#f87171}.sev.medium{background:#f59e0b22;color:#fbbf24}.sev.low{background:#3f3f4622;color:#a1a1aa}
.finding .ln{color:#22d3ee;min-width:44px}
.finding .msg{flex:1}
.finding .msg b{color:#fff}
.finding .sug{color:#71717a;font-size:12px;margin-top:2px}
.ai-tag{display:inline-block;background:#22d3ee22;color:#22d3ee;font-size:10px;font-weight:700;padding:1px 6px;border-radius:5px;margin-left:8px;vertical-align:1px}
.tests{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:18px 22px;margin-top:22px}
.tests h2{font-size:15px;color:#fff;margin-bottom:8px}
.tests pre{background:#09090b;border:1px solid #27272a;border-radius:8px;padding:12px;font-size:12px;color:#a1a1aa;margin-top:10px;white-space:pre-wrap;max-height:220px;overflow:auto}
.empty{color:#52525b;padding:20px 0;font-size:14px}
.legend{margin-top:18px;font-size:12px;color:#52525b}
</style>\n</head>\n<body>\n<div class=\"wrap\">\n`)
	fmt.Fprintf(&b, "<h1>Verification Report</h1>\n<div class=\"mode\">mode: %s · generated by devkit</div>\n", html.EscapeString(r.Mode))
	b.WriteString(verdictBanner(r.Verdict))
	b.WriteString(`<div class="chips">
  <div class="chip"><div class="k">Findings</div><div class="v">` + fmt.Sprint(r.Total) + `</div></div>
  <div class="chip"><div class="k">High</div><div class="v red">` + fmt.Sprint(r.High) + `</div></div>
  <div class="chip"><div class="k">Medium</div><div class="v yellow">` + fmt.Sprint(r.Medium) + `</div></div>
  <div class="chip"><div class="k">Low</div><div class="v">` + fmt.Sprint(r.Low) + `</div></div>
  <div class="chip"><div class="k">Risk</div><div class="v">` + html.EscapeString(r.Risk) + `</div></div>
  <div class="chip"><div class="k">AI signal</div><div class="v cyan">` + html.EscapeString(r.AiSignal) + `</div></div>
  <div class="chip"><div class="k">AI lines</div><div class="v">` + fmt.Sprintf("%d/%d", r.AiLines, r.AiTotal) + `</div></div>
</div>
`)
	b.WriteString(fileCards(r))
	b.WriteString(testsCard(r))
	b.WriteString(`<div class="legend">AI attribution is a heuristic estimate from generated markers, echo comments, essay-style docblocks, type widening and swallowed errors — review flagged lines manually before merge.</div>
</div>
</body>
</html>
`)

	return b.String()
}

func verdictBanner(verdict string) string {
	cls, icon := "pass", "✓"
	switch verdict {
	case "ACTION NEEDED":
		cls, icon = "action", "!"
	case "BLOCK":
		cls, icon = "block", "✗"
	}
	return fmt.Sprintf(`<div class="verdict %s">%s VERDICT: %s</div>`, cls, icon, html.EscapeString(verdict))
}

func fileCards(r Report) string {
	var b strings.Builder
	if len(r.Files) == 0 {
		return `<div class="empty">No issues found in the verified changes.</div>`
	}
	for _, fr := range r.Files {
		ai := r.Attribution[fr.File]
		pct := int(ai.Pct * 100)
		fmt.Fprintf(&b, `<div class="file"><h2>%s</h2><div class="meta">%d line(s) · AI attribution: %d%% (%d line(s))</div><div class="ai-bar"><span style="width:%d%%"></span></div>`,
			html.EscapeString(fr.File), fr.LineCount, pct, ai.AiLines, pct)
		for _, f := range fr.Findings {
			aiTag := ""
			if f.Category == "ai" {
				aiTag = `<span class="ai-tag">AI</span>`
			}
			fmt.Fprintf(&b, `<div class="finding"><span class="sev %s">%s</span><span class="ln">L%d</span><div class="msg"><b>%s</b>%s<span class="sug">%s</span></div></div>`,
				f.Severity, strings.ToUpper(f.Severity), f.Line, html.EscapeString(f.Message), aiTag, html.EscapeString(f.Suggestion))
		}
		b.WriteString(`</div>`)
	}
	return b.String()
}

func testsCard(r Report) string {
	var b strings.Builder
	b.WriteString(`<div class="tests"><h2>Automated tests</h2>`)
	if !r.Tests.Ran {
		b.WriteString(`<div class="empty">No tests run — use <b>dev verify --tests</b> to run the project suite as part of verification.</div>`)
	} else {
		state := `<span style="color:#4ade80">PASSED</span>`
		if !r.Tests.Passed {
			state = `<span style="color:#f87171">FAILED</span>`
		}
		fmt.Fprintf(&b, `<div class="empty"><b>%s</b> · %s · %s</div><pre>%s</pre>`,
			state, html.EscapeString(r.Tests.Command), html.EscapeString(r.Tests.Duration), html.EscapeString(r.Tests.Output))
	}
	b.WriteString(`</div>`)
	return b.String()
}

// WriteHTML writes the visual report to a file.
func WriteHTML(r Report, path string) error {
	return os.WriteFile(path, []byte(RenderHTML(r)), 0o644)
}

// OpenHTML writes the report and opens it in the default browser.
func OpenHTML(r Report, path string) error {
	if err := WriteHTML(r, path); err != nil {
		return err
	}
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", path)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", path)
	default:
		cmd = exec.Command("xdg-open", path)
	}
	return cmd.Start()
}
