package verify

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestScanLinesCatchesSecurityIssues(t *testing.T) {
	lines := []string{
		`const API_KEY = "sk_live_1234567890abcdef";`,
		`eval(input);`,
		`el.innerHTML = data;`,
		`const pw = "hunter2";`,
	}
	nums := []int{10, 11, 12, 13}
	findings := scanLines("app.ts", nums, lines)

	got := map[string]bool{}
	for _, f := range findings {
		got[f.Rule] = true
		if f.Line < 10 {
			t.Errorf("line number lost in diff: got %d want >=10", f.Line)
		}
	}
	for _, want := range []string{"credential-value", "code-execution", "xss-innerhtml", "hardcoded-secret"} {
		if !got[want] {
			t.Errorf("expected rule %q to fire", want)
		}
	}
}

func TestScanLinesAIAttribution(t *testing.T) {
	lines := []string{"// This code was generated by Copilot", "const x = 1;"}
	findings := scanLines("gen.ts", []int{1, 2}, lines)

	found := false
	for _, f := range findings {
		if f.Rule == "ai-generated-marker" && f.Category == "ai" {
			found = true
		}
	}
	if !found {
		t.Error("expected ai-generated-marker rule to fire")
	}
}

func TestScanLinesClean(t *testing.T) {
	lines := []string{"export function ok(a: number): number {", "  return a;", "}"}
	findings := scanLines("good.ts", []int{1, 2, 3}, lines)
	if len(findings) != 0 {
		t.Errorf("expected no findings, got %d", len(findings))
	}
}

func TestParseDiffLineNumbers(t *testing.T) {
	diff := `diff --git a/app.ts b/app.ts
index abc..def 100644
--- a/app.ts
+++ b/app.ts
@@ -1,3 +1,5 @@
 export const greeting = "hi";
+const KEY = "sk_test_1234567890abcdef";
+function boom() {
+  eval(x);
+}
`
	files := parseDiff(diff)
	fc, ok := files["app.ts"]
	if !ok {
		t.Fatal("expected app.ts in parsed diff")
	}
	if len(fc.contents) != 4 {
		t.Fatalf("expected 4 added lines, got %d: %v", len(fc.contents), fc.contents)
	}
	want := []int{2, 3, 4, 5}
	for i, w := range want {
		if fc.nums[i] != w {
			t.Errorf("line %d: got %d want %d", i, fc.nums[i], w)
		}
	}
}

func TestAnalyzeVerdict(t *testing.T) {
	files := map[string]fileContent{
		"app.ts": {
			contents: []string{`const KEY = "sk_test_1234567890";`},
			nums:     []int{1},
		},
	}
	r := analyze("staged", files, false)
	if r.Verdict != "BLOCK" {
		t.Errorf("expected BLOCK verdict, got %s", r.Verdict)
	}
	if r.High != 1 {
		t.Errorf("expected 1 high, got %d", r.High)
	}
	if r.AIlikelihood != "No AI markers" {
		t.Errorf("unexpected AI label: %s", r.AIlikelihood)
	}
}

func TestReportJSONSerializable(t *testing.T) {
	files := map[string]fileContent{
		"a.ts": {contents: []string{"console.log(1);"}, nums: []int{5}},
	}
	r := analyze("file", files, false)
	out, err := json.Marshal(r)
	if err != nil {
		t.Fatalf("report must be JSON-serializable: %v", err)
	}
	if !strings.Contains(string(out), "console.log") {
		t.Errorf("JSON output missing finding: %s", out)
	}
}
